Apple Store Model Dev
fivetran/dbt_apple_store pull request #1
Opened 2022-03-30 19:06 UTC by fivetran-sheringuyen

2022-04-04 20:49 UTC, fivetran-joemarkiewicz requested changes
@fivetran-sheringuyen great job with these models and working through the Apple App Store data!! 🙌 

Unfortunately, since my primary work laptop has bricked 🧱  I wasn't able to actually look at the source data or fully test the package models. However, I did my best to look critically at the sql logic for each of your models and have a few style, standards, and transformation questions in the comments below. Let me know if you have any questions!

Also, please be aware that I may have more questions come the final review when I am able to actually run the package and view the data. 😭

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/apple_store__device_report.sql
> +, crashes_device_report as (
Is this correct formatting? I feel like this looks weird. Can we do the below instead?
```suggestion
with app_store_device_report as (

    select *
    from {{ var('app_store_device_report') }}
), 

downloads_device_report as (

    select *
    from {{ var('downloads_device_report') }}
),

usage_device_report as (

    select *
    from {{ var('usage_device_report') }}
), 

crashes_device_report as (
```

If so, then can we update the rest of the models and our style guide as well. Open to your thoughts!

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/apple_store__device_report.sql
> +    union
Why not `union all`?

Could we accidentally be removing duplicates incorrectly here with just `union`?

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/apple_store__device_report.sql
> +    union
Could we maybe leverage [dbt_utils.union_relations()](https://github.com/dbt-labs/dbt-utils#union_relations-source) here to make the code a bit drier?

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/apple_store__device_report.sql
> +    union
Similar question for other models.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/apple_store__device_report.sql
> +        coalesce(crashes_device_report.crashes, 0) as crashes
Are `null` and `0` the same when it comes to crashes? I am thinking in terms of users not sending data back to Apple. If that were the case then `null` may not necessarily mean `0` crashes.

This may just be something we need to highlight in our docs.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/apple_store__source_type_report.sql
> +    from downloads_source_type_report
Could we use union_relation here to make the code drier? Or would that sacrifice readability?

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +            {% endfor %}
So cool!! ❄️

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +            when state is null or trim(state) = '' then 'Not Available' else state
Curious about this... Does Apple sometime just send empty records instead of `null` values?

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +            when state is null or trim(state) = '' then 'Not Available' else state
Also, be careful with `trim`. This version of `trim` I do not believe is compatible with Postgres. I ran into this a month or so ago and even opened up a branch which added `trim` as a [fivetran_util](https://github.com/fivetran/dbt_fivetran_utils/compare/releases/v0.3.latest...feature/trim-macro) macro.

However, I ended up just using `replace`. Could we use that here instead?

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_summary.sql
> +            when state is null or trim(state) = '' then 'Not Available' else state
Same `trim` comment.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/apple_store__subscriptions_report.sql
> +with subscription_summary as (
I would imagine we need to add the `config(enabled=var("using_subscriptions"))` block to this model since it is dealing with subscriptions that can be disabled.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/apple_store__subscriptions_report.sql
> +        {% endfor %}
This looks right, but I am not able to test this without access to the data. I will test further once I have my machine up and running.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +with base as (
I would imagine we need to add the `config(enabled=var("using_subscriptions"))` block to this model since it is dealing with subscriptions that can be disabled.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +            {% endfor %}
Similar to previous comment, I want to test this further once I can access data.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +        , sum(case when lower(event) = '{{ event_val | trim | lower }}' then quantity else 0 end) as {{ 'event_' ~ event_val | replace(' ', '_') | trim | lower }}
May be a dumb question, but can we confirm that `quantity` will always be a numeric field? Thinking of our time on the Klaviyo package with this same issue.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +        country,
Per our style guide we should alias these, right?

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +            when state is null or trim(state) = '' then 'Not Available' else state
Also, same alias comment as above.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_summary.sql
> +with base as (
I would imagine we need to add the `config(enabled=var("using_subscriptions"))` block to this model since it is dealing with subscriptions that can be disabled.

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_summary.sql
> +        country,
Same alias comment

2022-04-04 20:49 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_summary.sql
> +    left join sales_account on base.account_id = sales_account.account_id
Based on our new style guide, these should be formatted with the `on` as a new line, right?

2022-04-04 21:26 UTC, fivetran-sheringuyen commented on dbt_project.yml
> +      - 'Downgrade'
@fivetran-joemarkiewicz Great question! There are at least 26 events total (trying to confirm with a couple of our sources). I reviewed all the 26 events and referred to a couple different Apple resources to select a subset that I felt could be the most useful.

2022-04-04 21:27 UTC, fivetran-sheringuyen commented on models/apple_store__device_report.sql
> +, crashes_device_report as (
Good catch, will incorporate to align with the style guide!

2022-04-04 21:47 UTC, fivetran-sheringuyen commented on models/apple_store__device_report.sql
> +    union
Great call out Joe! 

So this "reporting grain" logic is using `union` rather than `union all` because we want to only use the grains that appear for any given day. I actually just followed this same convention for all the models after I did the subscription events model since the reporting doesn't report every country-state combination everyday. 

However, I just did a double check and it actually looks like this `reporting_grain` logic is only needed for the subscriptions_event models as every other report will report the same number of unique row combinations each day. Will update the other 3 models!

2022-04-04 21:50 UTC, fivetran-sheringuyen commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +        , sum(case when lower(event) = '{{ event_val | trim | lower }}' then quantity else 0 end) as {{ 'event_' ~ event_val | replace(' ', '_') | trim | lower }}
I think that's a great call out Joe! In our macros, we specify that it is an integer field (unlike in Klaviyo).

2022-04-04 21:56 UTC, fivetran-sheringuyen commented on models/apple_store__source_type_report.sql
> +    from downloads_source_type_report
ref previous comment response

2022-04-04 21:57 UTC, fivetran-sheringuyen commented on models/apple_store__device_report.sql
> +        coalesce(crashes_device_report.crashes, 0) as crashes
Great call out! i added into the the yml a note for this description. I think it will suffice to add to the yml that "a value of 0 crashes would indicate that there were no reported crashes that day".

2022-04-04 22:07 UTC, fivetran-sheringuyen commented
Heya @fivetran-joemarkiewicz, I responded & made the appropriate adjustments! Thank you for all the good call outs re:style, I had finished a good half of the package before reviewing the style guide and forgot to go back and update the style to what we ended up agreeing on but all the changes have been incorporated!

2022-04-04 23:16 UTC, fivetran-joemarkiewicz commented on dbt_project.yml
> +      - 'Downgrade'
Thanks @fivetran-sheringuyen! This makes sense and I like the approach. 

For the "polish" task, we should just remember to add a link to the 26 possible events in our yml docs and our README notes on this variable.

2022-04-04 23:17 UTC, fivetran-joemarkiewicz commented on models/apple_store__device_report.sql
> +    union
Awesome thanks so much! And that makes sense for the sub models. I honestly hadn't dug further into `union` and `union all` until today haha

2022-04-04 23:18 UTC, fivetran-joemarkiewicz commented on models/apple_store__device_report.sql
> +        coalesce(crashes_device_report.crashes, 0) as crashes
Sounds great, thanks!

2022-04-05 17:12 UTC, fivetran-sheringuyen commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +            when state is null or trim(state) = '' then 'Not Available' else state
I wasn't sure if there'd be a case for null and for trim -- so I kept both. But I could just keep trim and remove the null and if there are any issues down the line re: this then we will know how to diagnose.

Let me give your trim a try! Was there a reason why it wasn't merged and released with the last release of fivetran_utils?

2022-04-05 19:18 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_apple_store__sales_subscription_event_summary.sql
> +            when state is null or trim(state) = '' then 'Not Available' else state
We ended up not merging `trim` since replace was a simpler solution and was less complex for cross db compatiblity.

2022-04-05 19:20 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-sheringuyen thanks so much for applying these updates and addressing my questions 💯 

This looks great and feel free to merge into `main`! 🔀

2022-04-05 22:05 UTC, merged