update field descriptions
fivetran/dbt_apple_store pull request #14
Opened 2023-07-18 18:33 UTC by fivetran-reneeli

## PR Overview
**This PR will address the following Issue/Feature:**

**This PR will result in the following new package version:**

**Please detail what change(s) this PR introduces and any additional information that should be known during the review of this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt compile
- [ ] dbt run –full-refresh
- [ ] dbt run
- [ ] dbt test
- [ ] dbt run –vars (if applicable)

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked and tagged
- [ ] You are assigned to the corresponding issue and this PR
- [ ] BuildKite integration tests are passing

### Detailed Validation
Please acknowledge that the following validation checks have been performed prior to marking this PR as "ready for review":
- [ ] You have validated these changes and assure this PR will address the respective Issue/Feature.
- [ ] You are reasonably confident these changes will not impact any other components of this package or any dependent packages.
- [ ] You have provided details below around the validation steps performed to gain confidence in these changes.

### Standard Updates
Please acknowledge that your PR contains the following standard updates:
- Package versioning has been appropriately indexed in the following locations:
    - [ ] indexed within dbt_project.yml
    - [ ] indexed within integration_tests/dbt_project.yml
- [ ] CHANGELOG has individual entries for each respective change in this PR
    
- [ ] README updates have been applied (if applicable)
    
- [ ] DECISIONLOG updates have been updated (if applicable)
- [ ] Appropriate yml documentation has been added (if applicable)

### dbt Docs
Please acknowledge that after the above were all completed the below were applied to your branch:
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2023-07-19 19:55 UTC, fivetran-reneeli commented
- [ ] dbt docs after review is completed

2023-07-25 15:54 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for making this update! There are just a few more updates needed to be applied before this will be good to approve. 

Let me know once this is ready for re-review!

2023-07-25 15:54 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +# dbt_apple_store v0.3.1
It looks like this was missed by chance

2023-07-25 15:54 UTC, fivetran-joemarkiewicz commented on models/apple_store.yml
> +      #   description: '{{ doc("total_downloads") }}'
Should these be fully removed?

2023-07-25 15:54 UTC, fivetran-joemarkiewicz commented on packages.yml
> +  warn-unpinned: false
Reminder to update before merge

2023-07-25 18:58 UTC, fivetran-reneeli commented on CHANGELOG.md
> +# dbt_apple_store v0.3.1
updated

2023-07-25 18:58 UTC, fivetran-reneeli commented on models/apple_store.yml
> +      #   description: '{{ doc("total_downloads") }}'
yes removed!

2023-07-25 19:49 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for working through this. This looks good, but I do wonder if we are including more changes than necessary. I am fairly certain if you update the docs.md in the source package, they persist to the transform package. If that is in fact the case, may you remove those updates in this PR and update the changelog accordingly.

2023-07-25 19:49 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
>  ## Under the Hood:
I would also include an under the hood of adding some additional fields to the yml descriptions as this was also done in the PR and there were a number of them.

2023-07-25 19:49 UTC, fivetran-joemarkiewicz commented on models/docs.md
> +{% docs total_downloads %} Total Downloads is the sum of Redownloads and First Time Downloads. {% enddocs %}
Do these need to be added? I actually am pretty sure that the source package docs.md are automatically leveraged in the downstream models. This is a big benefit so we don't need to maintain the same descriptions in multiple places. If you remove these, do you see the docs still persist?

2023-07-25 19:49 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- Shortened the field description for `source_type`. This was causing an error if the persist docs config was enabled because the description size exceeded warehouse constraints.
Following my previous comment, this may not actually need to be done in this PR. I am pretty sure this is covered by the source package PR. If that is the case, you can mention that this was updated in the upstream release.

2023-07-25 19:54 UTC, fivetran-reneeli commented on models/docs.md
> +{% docs total_downloads %} Total Downloads is the sum of Redownloads and First Time Downloads. {% enddocs %}
Ah you're right, the docs from source do persist which is why they weren't here in the first place. I thought of bringing it here just to keep things standard across both packages but that's true, it'd just be one more thing to maintain and it'll persist downstream anyways. I'll remove it from the transforms

2023-07-25 20:08 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- Shortened the field description for `source_type`. This was causing an error if the persist docs config was enabled because the description size exceeded warehouse constraints.
changelog is updated

2023-07-25 20:41 UTC, fivetran-joemarkiewicz approved these changes
One small comment. Once that is addressed this is good to go!

2023-07-25 20:41 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
>  ## Under the Hood:
Would you also be able to add that yml descriptions were added/removed to the under the hood section. You don't need to include all the fields that were added/removed, but still reference that this was done.

2023-07-26 17:29 UTC, merged