Dev/modeling pt2
fivetran/dbt_apple_store pull request #2
Opened 2022-04-13 18:00 UTC by fivetran-sheringuyen

2022-04-18 21:10 UTC, fivetran-joemarkiewicz requested changes
@fivetran-sheringuyen thanks for all your hard work on pushing this package along and for adding these final models to the package! I have a few comments in line that I would like you to address before we merge this. Let me know if you have any questions!

One recurring question I had was around the `apple_store__using_downloads` variable and if this is still needed? I made a few comments about if this variable needs to be used to disable certain models (I didn't add it in ever place needed) but it seems this may not even bee needed anymore. What are your thoughts?

Also, it seems there are some merge conflicts that need to be resolved.

2022-04-18 21:10 UTC, fivetran-joemarkiewicz commented on models/intermediate/overview_report/int_apple_store__sales_subscription_overview_report.sql
> +with subscription_summary as (
Should this have a config to disable in case people do not have the subscription data in their source?

2022-04-18 21:10 UTC, fivetran-joemarkiewicz commented on models/intermediate/overview_report/int_apple_store__downloads_overview_report.sql
> +with base as (
Does this need the `apple_store__using_downloads` config enabled block? Or is this variable going to be scratched?

2022-04-18 21:10 UTC, fivetran-joemarkiewicz commented on models/intermediate/source_type_report/int_apple_store__downloads_source_type_report.sql
> +with base as (
Does this need the `apple_store__using_downloads` config enabled block or will this variable be scratched?

2022-04-18 21:10 UTC, fivetran-joemarkiewicz commented on models/apple_store__device_report.sql
> +),
Should we disable this with the `apple_store__using_downloads` variable, or is that not needed anymore?

2022-04-18 21:22 UTC, fivetran-joemarkiewicz commented
One last note is that I saw `fivetran_utils` was commented out of the source package. Was there a reason for this?

2022-04-18 21:52 UTC, fivetran-sheringuyen commented on models/apple_store__platform_version_report.sql
> +with app as (
Hi Joe! I think that `downloads_*` tables should be incorporated by all customers. So we should not allow this table to be configurable.

2022-04-18 21:59 UTC, fivetran-sheringuyen commented on models/intermediate/subscriptions_report/int_apple_store__sales_subscription_event_summary.sql
> +        , account_id
🤦‍♀️ Oh man, looks like I had made all the changes, committed and totally forgot to push the source package. This should be resolved now!

2022-04-18 22:00 UTC, fivetran-sheringuyen commented on models/intermediate/subscriptions_report/int_apple_store__sales_subscription_event_summary.sql
> +        sales_account.account_name,
ah changes that weren't pushed to the source 🤦‍♀️ ! I changed everything to be `account_name` so that it would be less convoluted!

2022-04-18 22:02 UTC, fivetran-sheringuyen commented on models/intermediate/overview_report/int_apple_store__downloads_overview_report.sql
> +with base as (
Variable has been scratched!

2022-04-18 22:15 UTC, fivetran-sheringuyen commented
Thanks for the PR review @fivetran-joemarkiewicz! How absolutely embarrassing -- it looks like I had committed all my changes to the source package but unfortunately forgot to actually _push_ the changes. So I went through and resolved all of the review comments that should be solved now. Big giant 🤦‍♀️ and my apologies for causing you the trouble. 

However, the two big questions you had seemed to be around the below:
1. Downloads configurability - I've scratched that from the package as downloads should be an integral part of customer reporting and should encourage customers to enable this model if they haven't already. But this brings up another great point, and I'm going to double check all the subscriptions tables and make sure that they are properly configured as well!
2. I had originally commented out Fivetran Utils in the source package because of the problem around accessing redshift for the get columns for macros (Jamie put in a fix that I was using!). I'll actually go update that now.

2022-04-18 22:15 UTC, fivetran-sheringuyen commented
Thanks for the PR review @fivetran-joemarkiewicz! How absolutely embarrassing -- it looks like I had committed all my changes to the source package but unfortunately forgot to actually _push_ the changes. So I went through and resolved all of the review comments that should be solved now. Big giant 🤦‍♀️ and my apologies for causing you the trouble. 

However, the two big questions you had seemed to be around the below:
1. Downloads configurability - I've scratched that from the package as downloads should be an integral part of customer reporting and should encourage customers to enable this model if they haven't already. But this brings up another great point, and I'm going to double check all the subscriptions tables and make sure that they are properly configured as well!
2. I had originally commented out Fivetran Utils in the source package because of the problem around accessing redshift for the get columns for macros (Jamie put in a fix that I was using!). I'll actually go update that now.

2022-04-19 18:30 UTC, fivetran-joemarkiewicz commented on models/apple_store__platform_version_report.sql
> +with app as (
Sounds good, thanks for the clarification!

2022-04-19 19:08 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-sheringuyen thanks so much for making the requested changes! This PR looks good 🏅 

I did just have one question around the default value for the `apple_store__using_subscriptions` variable. It seems we are inconsistent with the default value within the `dbt_project.yml` and the actual jinja conditionals.

2022-04-19 19:15 UTC, fivetran-sheringuyen commented on dbt_project.yml
> +    apple_store__using_subscriptions: false
I was testing to see if the the variable being set to false would work, I'll change that now!

2022-04-19 22:57 UTC, fivetran-sheringuyen commented on dbt_project.yml
> +    apple_store__using_subscriptions: false
btw I went and changed all the default values to False & removed the variable from the `dbt_project`.yml files!

2022-04-19 23:00 UTC, merged