Feature: Union schema compatibility
fivetran/dbt_apple_store pull request #22
Opened 2024-07-15 19:15 UTC by fivetran-catfritz

Issue: 

Confirm the following files were correctly updated automatically:
- [ ] CHANGELOG
- [ ] README
- [ ] stg_apple_store.yml, src_apple_store.yml, apple_store.yml (depending if source or transform)
- [ ] docs.md
- [ ] joins
- [ ] window functions (partition by)
- [ ] 'source_relation' column added in staging and transform models
- [ ] tests

Manual updates:
- [ ] Add `source_relation` to downstream models if necessary
- [ ] Finish any incomplete/incorrect joins/partitions
- [ ] Update tests to include `source_relation` in unique-combination-of-cols if necessary
    - May need to remove some uniqueness tests in favor of the combo test

Validation:
- [ ] `dbt run` locally passes
- [ ] `dbt test` locally passes

2024-07-19 19:24 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz great work on this PR! I just have a few small requests before approving this PR. Let me know if you have any questions. Thanks!

2024-07-19 19:24 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- To distinguish which source each field comes from, added `source_relation` column in each staging and downstream model and applied the `fivetran_utils.source_relation` macro.
This also has impacts in these end models as the `source_relation` is now a new field in all end models. We should highlight this in the feature update for the end models.

2024-07-22 21:01 UTC, fivetran-catfritz reviewed
@fivetran-joemarkiewicz I have updated, and this is ready for re-review!

2024-07-22 21:07 UTC, fivetran-joemarkiewicz approved these changes
LGTM thanks for applying the changes!

2024-07-23 23:28 UTC, merged